//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orderproducts = new HashSet<orderproduct>();
        }
    
        public int id { get; set; }
        public string NAME { get; set; }
        public Nullable<int> quantity { get; set; }
        public string imageurl { get; set; }
        public string description { get; set; }
        public string chip { get; set; }
        public string ram { get; set; }
        public string monitor { get; set; }
        public string harddrive { get; set; }
        public string power { get; set; }
        public string mainboard { get; set; }
        public string vga { get; set; }
        public string cpu { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:c}")]
        public Nullable<decimal> price { get; set; }
        public Nullable<int> brandid { get; set; }
    
        public virtual brand brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderproduct> orderproducts { get; set; }
    }
}
