//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string NAME { get; set; }
        public Nullable<int> quantity { get; set; }
        public string imageurl { get; set; }
        public string description { get; set; }
        public string chip { get; set; }
        public string ram { get; set; }
        public string monitor { get; set; }
        public string harddrive { get; set; }
        public string power { get; set; }
        public string mainboard { get; set; }
        public string vga { get; set; }
        public string cpu { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> brandid { get; set; }
    
        public virtual brand brand { get; set; }
    }
}
