//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoppingcartEntities : DbContext
    {
        public shoppingcartEntities()
            : base("name=shoppingcartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chip> chips { get; set; }
        public virtual DbSet<cpu> cpus { get; set; }
        public virtual DbSet<harddrive> harddrives { get; set; }
        public virtual DbSet<mainboard> mainboards { get; set; }
        public virtual DbSet<monitor> monitors { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<power> powers { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<ram> rams { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userorder> userorders { get; set; }
        public virtual DbSet<vga> vgas { get; set; }
    }
}
